import type { Metadata } from "next";
import "./globals.css";
import { alata, josefin } from "./fonts";



export const metadata: Metadata = {
  title: "loopstudios",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en"className={`${alata.variable} ${josefin.variable}`}>
    <body className="font-sans antialiased">
      {children}
    </body>
  </html>
  );
}
